version: "3.7"

services:
  app:
    container_name: "react-go-todo"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "9230:9230"
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - react-go-todo-mysql
      - react-go-todo-redis

  react-go-todo-mysql:
    platform: linux/amd64
    container_name: react-go-todo-mysql
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./compose/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    expose:
      - "1234"
    cap_add:
      - SYS_NICE
    ports:
      - "1234:5678"
    restart: "no"
    networks:
      - main

  react-go-todo-redis:
    image: redis:7.2
    container_name: react-go-todo-redis
    expose:
    - "9876"
    ports:
      - "9876:9876"
    volumes:
      - redis-data:/data
    networks:
      - main

networks:
  main:

volumes:
  mysql-data:
  redis-data: